services:

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    restart: always

  frontend:
    image: csc424lab9/frontendfinal:latest
    networks:
      - app-network
    restart: always

  backend:
    image: csc424lab9/backendfinal:latest
    environment:
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
